### PR TITLE
Update Safari support

### PR DESCRIPTION
**Pull request by lexaknyazev**
/cc @donmccurdy

### CODE REVIEW

**Review by bghgary — APPROVED** [review]
I have an old Intel-based MBP. I know you already mentions that only newer SoC supports all possible targets, but I was curious to see what was missing.

For Edge, I tried turning on Metal and now the browser is completely garbled, and I can't use it anymore. I managed to reset without being able to see anything. We might want to warn the reader about this. After I reset here are the missing extensions without using Metal:
- EXT_texture_compression_bptc
- WEBGL_compressed_texture_astc
- WEBGL_compressed_texture_etc
- WEBGL_compressed_texture_pvrtc

For Safari, it looks like these are missing:
- WEBGL_compressed_texture_astc
- WEBGL_compressed_texture_etc
- WEBGL_compressed_texture_pvrtc

It's odd that Chromium based browsers don't have `EXT_texture_compression_bptc` but Safari does.

**Comment by lexaknyazev** [comment]
1. Although Chromium's Metal backend is still work-in-progress, it should be quite stable as of today. Could you please check Chromium Canary whether it has the same issues? If so, please file a bug at https://crbug.com.
2. BPTC formats are not supported by Apple's OpenGL drivers (see footnote 1) so they can be used only with Metal.
3. Safari 16 on Monterey and newer uses Metal by default so BPTC formats are available there.

**Review by donmccurdy — APPROVED** [review]
Tested in Safari 16 and Chromium-based Arc (https://thebrowser.company/) with Metal backend enabled, on macOS + Apple Silicon. Extension list appears as expected, with the addition of `WEBGL_compressed_texture_etc1`. Thanks!

**Comment by bghgary** [comment]
> Could you please check Chromium Canary whether it has the same issues?

Same issue with latest Chrome Canary.

**Comment by bghgary** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1365598

**Pull request merged**
